// Unit tests for block-in-place gap detection in trace_parser.js.
// See docs/adr/0001 and docs/adr/0002.
//
// Migrated from test_block_in_place.js (T11); frozen core loaded via
// createRequire (see format.test.ts for the rationale). The integration test
// reads the committed fixture test-traces/block_in_place.bin (regenerated by
// scripts/regenerate_block_in_place_trace.sh).

import { describe, it, expect } from "vitest";
import { createRequire } from "node:module";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);

interface ParkEvent {
  eventType: number;
  timestamp: number;
  workerId: number;
  tid: number | undefined;
  cpuTime: number;
  schedWait: number;
  localQueue: number;
  globalQueue: number;
  taskId: number;
  spawnLocId: null;
  spawnLoc: null;
}

interface SampleEvent {
  timestamp: number;
  workerId: number;
  tid: number;
  source: number;
  callchain: string[];
  cpu: null;
}

interface Gap {
  workerId: number;
  fromTid: number;
  toTid: number;
  startNs: number;
  endNs: number;
}

const { EVENT_TYPES, OFF_WORKER_WORKER_ID, deriveBlockInPlaceGaps, parseTrace } =
  require("../../trace_parser.js") as {
    EVENT_TYPES: Record<string, number>;
    OFF_WORKER_WORKER_ID: number;
    deriveBlockInPlaceGaps: (events: ParkEvent[], samples: SampleEvent[]) => Gap[];
    parseTrace: (buf: Buffer) => Promise<{ blockInPlaceGaps: Gap[] }>;
  };

// Helpers to build synthetic events.
function unpark(t: number, w: number, tid: number | undefined): ParkEvent {
  return {
    eventType: EVENT_TYPES["WorkerUnpark"]!,
    timestamp: t,
    workerId: w,
    tid,
    cpuTime: 0,
    schedWait: 0,
    localQueue: 0,
    globalQueue: 0,
    taskId: 0,
    spawnLocId: null,
    spawnLoc: null,
  };
}

function park(t: number, w: number, tid: number | undefined): ParkEvent {
  return {
    eventType: EVENT_TYPES["WorkerPark"]!,
    timestamp: t,
    workerId: w,
    tid,
    cpuTime: 0,
    schedWait: 0,
    localQueue: 0,
    globalQueue: 0,
    taskId: 0,
    spawnLocId: null,
    spawnLoc: null,
  };
}

function sample(t: number, tid: number, wireWorkerId: number): SampleEvent {
  return {
    timestamp: t,
    workerId: wireWorkerId,
    tid,
    source: 0,
    callchain: [],
    cpu: null,
  };
}

describe("deriveBlockInPlaceGaps", () => {
  // Test 1 — No block_in_place. Same tid throughout, no gaps detected.
  it("no block_in_place: straight run has no gaps", () => {
    const events = [
      unpark(10, 0, 42),
      park(20, 0, 42),
      unpark(30, 0, 42),
      park(40, 0, 42),
    ];
    const samples = [
      sample(15, 42, 0), // during active
      sample(25, 42, 0), // while parked (wire still says W0)
      sample(35, 42, 0), // during second active
    ];
    const gaps = deriveBlockInPlaceGaps(events, samples);
    expect(gaps, "no gaps detected").toEqual([]);
    // No gap → no rewrite. workerId stays as wire value (0).
    expect(
      samples.map((s) => s.workerId),
      "no samples rewritten",
    ).toEqual([0, 0, 0]);
  });

  // Test 2 — Single block_in_place handoff.
  it("single block_in_place handoff", () => {
    const events = [
      unpark(10, 0, 42), // tid 42 takes worker 0
      park(50, 0, 99), // park on tid 99 — gap detected, [10, 50)
      unpark(60, 0, 99), // tid 99 now confirmed
      park(70, 0, 99),
    ];
    const samples = [
      sample(20, 42, 0), // in gap, on fromTid
      sample(30, 99, 255), // in gap, on toTid (wire said unknown — blocking)
      sample(65, 99, 0), // outside gap, after gap closed
      sample(20, 77, 255), // unrelated tid in gap window — should NOT be rewritten
    ];
    const gaps = deriveBlockInPlaceGaps(events, samples);
    expect(gaps, "one gap detected").toEqual([
      { workerId: 0, fromTid: 42, toTid: 99, startNs: 10, endNs: 50 },
    ]);
    expect(
      samples[0]!.workerId,
      "fromTid sample in gap rewritten to off-worker",
    ).toBe(OFF_WORKER_WORKER_ID);
    expect(
      samples[1]!.workerId,
      "toTid sample in gap rewritten to off-worker (unchanged but still 255)",
    ).toBe(OFF_WORKER_WORKER_ID);
    expect(
      samples[2]!.workerId,
      "post-gap sample on toTid keeps wire workerId",
    ).toBe(0);
    expect(
      samples[3]!.workerId,
      "unrelated tid in gap window is unchanged (still 255)",
    ).toBe(255);
  });

  // Test 3 — Sample at gap boundary. [start, end) is half-open.
  it("sample at gap boundaries: [start, end) half-open", () => {
    const events = [unpark(10, 0, 42), park(50, 0, 99)];
    const samples = [
      sample(10, 42, 0), // exactly at startNs — IN gap
      sample(50, 99, 0), // exactly at endNs — NOT in gap (half-open)
      sample(49, 99, 0), // just inside — IN gap
    ];
    deriveBlockInPlaceGaps(events, samples);
    expect(samples[0]!.workerId, "sample at gap startNs is in gap").toBe(
      OFF_WORKER_WORKER_ID,
    );
    expect(
      samples[1]!.workerId,
      "sample at gap endNs is NOT in gap (half-open)",
    ).toBe(0);
    expect(samples[2]!.workerId, "sample 1ns before endNs is in gap").toBe(
      OFF_WORKER_WORKER_ID,
    );
  });

  // Test 4 — Repeated block_in_place; original tid returns.
  it("repeated block_in_place, tid 42 returns", () => {
    const events = [
      unpark(10, 0, 42), // worker 0 = tid 42
      park(50, 0, 99), // gap 1: [10, 50), 42→99
      unpark(60, 0, 42), // gap 2: [50, 60), 99→42 (tid 42 reclaimed)
      park(70, 0, 42),
    ];
    const gaps = deriveBlockInPlaceGaps(events, []);
    expect(gaps, "two gaps detected").toEqual([
      { workerId: 0, fromTid: 42, toTid: 99, startNs: 10, endNs: 50 },
      { workerId: 0, fromTid: 99, toTid: 42, startNs: 50, endNs: 60 },
    ]);
  });

  // Test 5 — Multiple workers, one block_in_place.
  it("two workers, only W0 handoffs", () => {
    const events = [
      unpark(10, 0, 42),
      unpark(15, 1, 77),
      park(50, 0, 99), // W0 gap
      park(60, 1, 77), // W1 normal
    ];
    const gaps = deriveBlockInPlaceGaps(events, []);
    expect(gaps, "only W0's gap detected").toEqual([
      { workerId: 0, fromTid: 42, toTid: 99, startNs: 10, endNs: 50 },
    ]);
  });

  // Test 6 — Open binding at trace end (no closing park).
  it("open binding at trace end", () => {
    const events = [
      unpark(10, 0, 42),
      // No park before end of trace.
    ];
    const samples = [
      sample(50, 42, 0), // during open binding
    ];
    const gaps = deriveBlockInPlaceGaps(events, samples);
    expect(gaps, "no gap detected (no closing park)").toEqual([]);
    expect(samples[0]!.workerId, "sample retains wire workerId").toBe(0);
  });

  // Test 7 — Open binding at trace start (park-first, no preceding unpark).
  it("park without preceding unpark", () => {
    const events = [
      park(50, 0, 42), // first ever event for W0 is a park
      unpark(60, 0, 42), // re-unpark same tid: no gap
      park(70, 0, 42),
    ];
    const samples = [
      sample(20, 42, 0), // before any park/unpark
    ];
    const gaps = deriveBlockInPlaceGaps(events, samples);
    expect(gaps, "no gap detected (single tid throughout)").toEqual([]);
    expect(samples[0]!.workerId, "sample retains wire workerId").toBe(0);
  });

  // Test 8 — Long block_in_place chain across multiple tids.
  it("chain 42 -> 99 -> 77", () => {
    const events = [
      unpark(10, 0, 42),
      park(50, 0, 99), // gap 1: 42→99
      unpark(60, 0, 99),
      park(70, 0, 77), // gap 2: 99→77
      unpark(80, 0, 77),
    ];
    const gaps = deriveBlockInPlaceGaps(events, []);
    expect(gaps, "two gaps in chain").toEqual([
      { workerId: 0, fromTid: 42, toTid: 99, startNs: 10, endNs: 50 },
      { workerId: 0, fromTid: 99, toTid: 77, startNs: 60, endNs: 70 },
    ]);
  });

  // Test 9 — Sample on a tid that never appears in park/unpark.
  it("sample on unrelated tid keeps wire workerId", () => {
    const events = [unpark(10, 0, 42), park(50, 0, 99)];
    const samples = [
      sample(20, 555, 255), // tid 555 never seen as worker
      sample(30, 555, 0), // tid 555 with wire workerId 0 (wrong, kept as-is)
    ];
    deriveBlockInPlaceGaps(events, samples);
    expect(samples[0]!.workerId, "unrelated tid keeps its wire workerId").toBe(255);
    expect(
      samples[1]!.workerId,
      "unrelated tid keeps wire workerId even if it was wrongly populated",
    ).toBe(0);
  });

  // Bonus: old-format trace (no `tid` on park/unpark) → no-op.
  it("old-format trace without tid is no-op", () => {
    const events = [
      { ...unpark(10, 0, 42), tid: undefined },
      { ...park(50, 0, 99), tid: undefined },
    ];
    const samples = [sample(20, 42, 0), sample(30, 99, 0)];
    const gaps = deriveBlockInPlaceGaps(events, samples);
    expect(gaps, "no gaps without tid").toEqual([]);
    expect(
      samples.map((s) => s.workerId),
      "no samples rewritten without tid",
    ).toEqual([0, 0]);
  });

  // Integration test: decode a real trace with block_in_place gaps.
  const fixturePath = fileURLToPath(
    new URL("../../test-traces/block_in_place.bin", import.meta.url),
  );
  it("integration: real block_in_place trace", async () => {
    expect(existsSync(fixturePath), `Trace file not found: ${fixturePath}`).toBe(true);
    const trace = await parseTrace(readFileSync(fixturePath));
    expect(
      trace.blockInPlaceGaps.length,
      "detected block_in_place gap(s)",
    ).toBeGreaterThan(0);

    // Each gap should have valid fields.
    for (const g of trace.blockInPlaceGaps) {
      expect(
        g.workerId != null && g.fromTid > 0 && g.toTid > 0,
        `gap has valid workerId=${g.workerId}, fromTid=${g.fromTid}, toTid=${g.toTid}`,
      ).toBe(true);
      expect(
        g.fromTid,
        `gap fromTid !== toTid (${g.fromTid} !== ${g.toTid})`,
      ).not.toBe(g.toTid);
      expect(
        g.endNs,
        `gap endNs > startNs (${g.endNs} > ${g.startNs})`,
      ).toBeGreaterThan(g.startNs);
    }
  });
});
