[package]
name = "cuda-profiling"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
candle-core = { version = "0.11.0", features = ["cuda"] }
dial9 = { path = "../../dial9", default-features = false }
dial9-perf-self-profile = { path="../../perf-self-profile", default-features=false features = ["cuda"] }
