// Parse-cost benchmark for the COLUMNAR sink path.
//
// Why this exists separately from bench_parse.js: that script is CommonJS and
// requires the frozen core directly, so it can only exercise the legacy fat-object
// path (`events: []` + per-event objects). Every sink in this directory is
// TypeScript ESM, so the columnar path - the one the viewer actually runs since
// the big-traces migration - had no benchmark at all, which is why per-event
// interning and column growth regressed unnoticed.
//
// Run with `npm run bench`. Each case parses the same demo trace; compare the
// sink-ful cases against `baseline (no sinks)` to price the columnar path.

import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { bench, describe } from "vitest";
import "./core-globals.js";
import { ColumnarEvents } from "./columnar-events.js";
import { ColumnarCpuSamples } from "./columnar-cpu-samples.js";
import { ColumnarSpanEvents } from "./columnar-span-events.js";
import { parseTrace } from "../../../trace_parser.js";
import type { ParseOptions } from "../../../trace_parser.js";

const TRACE = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../public/demo-trace.bin",
);

// Skipping beats failing here: the demo trace is regenerated by a script that
// needs Rust + DDB, so a fresh checkout can legitimately lack it.
const available = existsSync(TRACE);
const raw = available ? readFileSync(TRACE) : null;

/** A fresh ArrayBuffer per iteration - parseTrace consumes the buffer, and
 *  reusing one across runs would measure a detached-buffer error path. */
function bytes(): ArrayBuffer {
  if (raw === null) throw new Error("demo trace missing");
  return raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength) as ArrayBuffer;
}

describe.skipIf(!available)("parse: fat vs columnar sinks", () => {
  bench("baseline (no sinks)", async () => {
    await parseTrace(bytes(), {} as ParseOptions);
  });

  bench("columnar events only", async () => {
    await parseTrace(bytes(), { eventSink: new ColumnarEvents() } as ParseOptions);
  });

  bench("columnar events + cpu samples", async () => {
    await parseTrace(bytes(), {
      eventSink: new ColumnarEvents(),
      cpuSampleSink: new ColumnarCpuSamples(),
    } as ParseOptions);
  });

  // The viewer's real configuration. The gap between this and the row above is
  // the span-event sink, whose per-event `internStr(String(span_id))` on
  // ~unique ids is a known suspect.
  bench("viewer config (all three sinks)", async () => {
    await parseTrace(bytes(), {
      eventSink: new ColumnarEvents(),
      cpuSampleSink: new ColumnarCpuSamples(),
      spanEventSink: new ColumnarSpanEvents(),
    } as ParseOptions);
  });
});
